spring:
    profiles:
        active: dev
 
---
server:
  port: 3366
spring:
    profiles: dev
    application:
        name: application-dev2020-8-30

---
server:
  port: 3355
spring:
    profiles: test
    application:
        name: application-test